// <auto-generated />
using System;
using ArtSite.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtSite.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614224854_AddArtistInfo")]
    partial class AddArtistInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtSite.Shared.Models.ArtWork", b =>
                {
                    b.Property<int>("ArtWorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtWorkId"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Medium")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ArtWorkId");

                    b.HasIndex("LocationId");

                    b.ToTable("ArtWorks");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtistInfo", b =>
                {
                    b.Property<int>("ArtistInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistInfoId"));

                    b.Property<string>("ArtistStatement")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CV")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArtistInfoId");

                    b.ToTable("ArtistInfos");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtistInfoVersion", b =>
                {
                    b.Property<int>("ArtistInfoVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtistInfoVersionId"));

                    b.Property<int>("ArtistInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("ArtistStatement")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("CV")
                        .HasColumnType("text");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("VersionCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArtistInfoVersionId");

                    b.HasIndex("ArtistInfoId");

                    b.ToTable("ArtistInfoVersions");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtworkImage", b =>
                {
                    b.Property<int>("ArtworkImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArtworkImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ArtWorkId")
                        .HasColumnType("integer");

                    b.Property<string>("BucketPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("ArtworkImageId");

                    b.HasIndex("ArtWorkId");

                    b.ToTable("ArtworkImages");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollectionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShowId"));

                    b.Property<string>("ArtistStatement")
                        .HasColumnType("text");

                    b.Property<string>("Dates")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("ShowInfo")
                        .HasColumnType("text");

                    b.Property<string>("ShowType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("ShowId");

                    b.HasIndex("LocationId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ShowArtwork", b =>
                {
                    b.Property<int>("ShowArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShowArtworkId"));

                    b.Property<int>("ArtWorkId")
                        .HasColumnType("integer");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer");

                    b.HasKey("ShowArtworkId");

                    b.HasIndex("ArtWorkId");

                    b.HasIndex("ShowId", "ArtWorkId")
                        .IsUnique();

                    b.ToTable("ShowArtworks");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ShowImage", b =>
                {
                    b.Property<int>("ShowImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShowImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BucketPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer");

                    b.HasKey("ShowImageId");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowImages");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtWork", b =>
                {
                    b.HasOne("ArtSite.Shared.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtistInfoVersion", b =>
                {
                    b.HasOne("ArtSite.Shared.Models.ArtistInfo", "ArtistInfo")
                        .WithMany("Versions")
                        .HasForeignKey("ArtistInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtistInfo");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtworkImage", b =>
                {
                    b.HasOne("ArtSite.Shared.Models.ArtWork", "ArtWork")
                        .WithMany("ArtworkImages")
                        .HasForeignKey("ArtWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtWork");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.Show", b =>
                {
                    b.HasOne("ArtSite.Shared.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ShowArtwork", b =>
                {
                    b.HasOne("ArtSite.Shared.Models.ArtWork", "ArtWork")
                        .WithMany()
                        .HasForeignKey("ArtWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtSite.Shared.Models.Show", "Show")
                        .WithMany("ShowArtworks")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtWork");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ShowImage", b =>
                {
                    b.HasOne("ArtSite.Shared.Models.Show", "Show")
                        .WithMany("ShowImages")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtWork", b =>
                {
                    b.Navigation("ArtworkImages");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.ArtistInfo", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ArtSite.Shared.Models.Show", b =>
                {
                    b.Navigation("ShowArtworks");

                    b.Navigation("ShowImages");
                });
#pragma warning restore 612, 618
        }
    }
}
